apiVersion: automation.cloudbees.io/v1alpha1                                                                                                       
kind: workflow                                                                                                                                     
name: deployer                                                                                                                                     
                                                                                                                                                   
on:                                                                                                                                                
  workflow_call:                                                                                                                                   
    inputs:                                                                                                                                        
      environment:                                                                                                                                 
        type: string                                                                                                                               
        required: true                                                                                                                             
      manifest:                                                                                                                                    
        type: string                                                                                                                               
        required: true       
      kubeconfig:                                                                                                                                  
        type: string                                                                                                                               
        required: true                                                                                                                       
                                                                                                                                                   
jobs:                                                                                                                                              
  deploy-database:
    if: ${{ fromJSON(inputs.manifest)['ecommerce-database'].deploy }}
    uses: dnarlakanti-IN-297/ecommerce-database/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['ecommerce-database'].id }}
      environment: ${{ inputs.environment }}
      kubeconfig: ${{ inputs.kubeconfig }}                                                                                                        
    secrets: inherit                                                                                                                               
    vars: inherit                                                                                                                                
                                                                                                                                                   
  deploy-backend:
    needs: deploy-database
    if: ${{ fromJSON(inputs.manifest)['ecommerce-backend'].deploy }}
    uses: dnarlakanti-IN-297/ecommerce-backend/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['ecommerce-backend'].id }}
      environment: ${{ inputs.environment }}
      kubeconfig: ${{ inputs.kubeconfig }}
    secrets: inherit                                                                                                                               
    vars: inherit                                                                                                                                  
                                                                                                                                                   
  deploy-frontend:
    needs: deploy-backend
    if: ${{ fromJSON(inputs.manifest)['ecommerce-frontend'].deploy }}
    uses: dnarlakanti-IN-297/ecommerce-frontend/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['ecommerce-frontend'].id }}
      environment: ${{ inputs.environment }}
      kubeconfig: ${{ inputs.kubeconfig }}                                                                                                       
    secrets: inherit                                                                                                                               
    vars: inherit                                                                                                                                  
                  